<?php

declare(strict_types=1);

require __DIR__ . '/bootstrap.php';
require __DIR__ . '/panel.php';

try { $pdo->query('SELECT 1 FROM pelish_products LIMIT 1'); } catch (PDOException $exception) { header('Location: setup.php'); exit; }

$pages = ['dashboard', 'products', 'orders', 'marketplaces', 'vouchers', 'customers', 'reports', 'catalog'];
$page = in_array($_GET['page'] ?? 'dashboard', $pages, true) ? (string) $_GET['page'] : 'dashboard';

function form_value(string $key, string $default = ''): string { return trim((string) ($_POST[$key] ?? $default)); }
function form_number(string $key): float { return (float) str_replace(',', '.', (string) ($_POST[$key] ?? 0)); }
function form_active(): int { return isset($_POST['is_active']) ? 1 : 0; }
function slug_name(string $value): string { $value = strtr(mb_strtolower($value, 'UTF-8'), ['ç'=>'c','ğ'=>'g','ı'=>'i','ö'=>'o','ş'=>'s','ü'=>'u']); return trim((string) preg_replace('/[^a-z0-9]+/', '-', $value), '-') ?: 'pelish-'.date('YmdHis'); }
function redirect_page(string $page, array $query = []): never { header('Location: '.admin_url($page, $query)); exit; }
function option_list(array $values, string $selected = ''): void { foreach ($values as $key => $value) { $optionValue = is_string($key) ? $key : (string) $value; ?><option value="<?= e($optionValue) ?>" <?= $optionValue === $selected ? 'selected' : '' ?>><?= e((string) $value) ?></option><?php } }
function confirm_button(string $action, int $id, string $message, array $extra = []): void { ?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="<?=e($action)?>"><input type="hidden" name="id" value="<?=$id?>"><?php foreach($extra as $name=>$value):?><input type="hidden" name="<?=e($name)?>" value="<?=e((string)$value)?>"><?php endforeach?><button class="danger-button" data-confirm="<?=e($message)?>" title="Sil"><i class="fa-solid fa-trash"></i></button></form><?php }
function modal(string $page, string $label, string $title, string $content): void { ?>
  <div class="modal <?= (isset($_GET['new']) || isset($_GET['edit'])) ? 'is-open' : '' ?>"><div class="modal-dialog"><div class="modal-head"><div><span><?=e($label)?></span><h2><?=e($title)?></h2></div><a class="modal-close" href="<?=admin_url($page)?>">×</a></div><?=$content?></div></div>
<?php }

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf(); $action = (string) ($_POST['action'] ?? '');
    if ($action === 'save-product') {
        $id=(int)($_POST['id']??0); $data=['name'=>form_value('name'),'category'=>form_value('category','Genel')?:'Genel','sku'=>form_value('sku')?:'PELISH-'.date('ymdHis'),'barcode'=>form_value('barcode')?:null,'image_url'=>form_value('image_url')?:null,'sale_price'=>form_number('sale_price'),'list_price'=>form_number('list_price'),'cost_price'=>form_number('cost_price'),'stock'=>max(0,(int)($_POST['stock']??0)),'desi'=>max(0,form_number('desi')),'is_active'=>form_active()];
        if ($data['name']==='') { admin_flash('danger','Ürün adı zorunludur.'); redirect_page('products',['new'=>1]); }
        try { if($id){$data['id']=$id;$pdo->prepare('UPDATE pelish_products SET name=:name,category=:category,sku=:sku,barcode=:barcode,image_url=:image_url,sale_price=:sale_price,list_price=:list_price,cost_price=:cost_price,stock=:stock,desi=:desi,is_active=:is_active WHERE id=:id')->execute($data);}else{$pdo->prepare('INSERT INTO pelish_products (name,category,sku,barcode,image_url,sale_price,list_price,cost_price,stock,desi,is_active) VALUES (:name,:category,:sku,:barcode,:image_url,:sale_price,:list_price,:cost_price,:stock,:desi,:is_active)')->execute($data);} admin_flash('success',$id?'Ürün güncellendi.':'Yeni ürün oluşturuldu.'); } catch(PDOException $e){admin_flash('danger','Ürün kodu benzersiz olmalıdır.');} redirect_page('products');
    }
    if ($action === 'delete-product' || $action === 'toggle-product') { $pdo->prepare($action==='delete-product'?'DELETE FROM pelish_products WHERE id=?':'UPDATE pelish_products SET is_active=IF(is_active=1,0,1) WHERE id=?')->execute([(int)$_POST['id']]); admin_flash('success',$action==='delete-product'?'Ürün silindi.':'Ürün durumu güncellendi.'); redirect_page('products'); }
    if ($action === 'save-customer') {
        $id=(int)($_POST['id']??0);$data=['first_name'=>form_value('first_name'),'last_name'=>form_value('last_name'),'email'=>form_value('email'),'phone'=>form_value('phone')?:null,'city'=>form_value('city')?:null,'district'=>form_value('district')?:null,'is_active'=>form_active()];
        if($data['first_name']===''||$data['last_name']===''||!filter_var($data['email'],FILTER_VALIDATE_EMAIL)){admin_flash('danger','Ad, soyad ve geçerli e-posta zorunludur.');redirect_page('customers',['new'=>1]);}
        try{if($id){$data['id']=$id;$pdo->prepare('UPDATE pelish_customers SET first_name=:first_name,last_name=:last_name,email=:email,phone=:phone,city=:city,district=:district,is_active=:is_active WHERE id=:id')->execute($data);}else{$pdo->prepare('INSERT INTO pelish_customers (first_name,last_name,email,phone,city,district,is_active) VALUES (:first_name,:last_name,:email,:phone,:city,:district,:is_active)')->execute($data);}admin_flash('success',$id?'Müşteri güncellendi.':'Yeni müşteri eklendi.');}catch(PDOException $e){admin_flash('danger','Bu e-posta zaten kullanılıyor.');}redirect_page('customers');
    }
    if ($action==='delete-customer'||$action==='toggle-customer'){$pdo->prepare($action==='delete-customer'?'DELETE FROM pelish_customers WHERE id=?':'UPDATE pelish_customers SET is_active=IF(is_active=1,0,1) WHERE id=?')->execute([(int)$_POST['id']]);admin_flash('success',$action==='delete-customer'?'Müşteri silindi.':'Müşteri durumu güncellendi.');redirect_page('customers');}
    if ($action === 'save-marketplace') {
        $id=(int)($_POST['id']??0);$data=['name'=>form_value('name'),'marketplace'=>form_value('marketplace'),'store_code'=>form_value('store_code')?:null,'commission_rate'=>max(0,form_number('commission_rate')),'is_active'=>form_active()];if($data['name']===''||$data['marketplace']===''){admin_flash('danger','Mağaza adı ve pazaryeri zorunludur.');redirect_page('marketplaces',['new'=>1]);}if($id){$data['id']=$id;$pdo->prepare('UPDATE pelish_marketplaces SET name=:name,marketplace=:marketplace,store_code=:store_code,commission_rate=:commission_rate,is_active=:is_active WHERE id=:id')->execute($data);}else{$pdo->prepare('INSERT INTO pelish_marketplaces (name,marketplace,store_code,commission_rate,is_active) VALUES (:name,:marketplace,:store_code,:commission_rate,:is_active)')->execute($data);}admin_flash('success',$id?'Mağaza güncellendi.':'Yeni mağaza eklendi.');redirect_page('marketplaces');
    }
    if (in_array($action,['delete-marketplace','toggle-marketplace','sync-marketplace'],true)){$sql=$action==='delete-marketplace'?'DELETE FROM pelish_marketplaces WHERE id=?':($action==='toggle-marketplace'?'UPDATE pelish_marketplaces SET is_active=IF(is_active=1,0,1) WHERE id=?':'UPDATE pelish_marketplaces SET last_sync_at=NOW() WHERE id=?');$pdo->prepare($sql)->execute([(int)$_POST['id']]);admin_flash('success',$action==='sync-marketplace'?'Senkronizasyon zamanı yenilendi.':($action==='delete-marketplace'?'Mağaza silindi.':'Mağaza durumu güncellendi.'));redirect_page('marketplaces');}
    if ($action === 'save-voucher') {
        $id=(int)($_POST['id']??0);$data=['code'=>mb_strtoupper(form_value('code'),'UTF-8'),'title'=>form_value('title'),'amount_type'=>($_POST['amount_type']??'')==='fixed'?'fixed':'percent','amount'=>max(0,form_number('amount')),'min_cart_total'=>max(0,form_number('min_cart_total')),'usage_limit'=>(($_POST['usage_limit']??'')==='')?null:max(0,(int)$_POST['usage_limit']),'starts_at'=>form_value('starts_at')?:null,'ends_at'=>form_value('ends_at')?:null,'is_active'=>form_active()];if($data['code']===''||$data['title']===''){admin_flash('danger','Kupon kodu ve başlığı zorunludur.');redirect_page('vouchers',['new'=>1]);}try{if($id){$data['id']=$id;$pdo->prepare('UPDATE pelish_vouchers SET code=:code,title=:title,amount_type=:amount_type,amount=:amount,min_cart_total=:min_cart_total,usage_limit=:usage_limit,starts_at=:starts_at,ends_at=:ends_at,is_active=:is_active WHERE id=:id')->execute($data);}else{$pdo->prepare('INSERT INTO pelish_vouchers (code,title,amount_type,amount,min_cart_total,usage_limit,starts_at,ends_at,is_active) VALUES (:code,:title,:amount_type,:amount,:min_cart_total,:usage_limit,:starts_at,:ends_at,:is_active)')->execute($data);}admin_flash('success',$id?'Hediye çeki güncellendi.':'Yeni hediye çeki oluşturuldu.');}catch(PDOException $e){admin_flash('danger','Bu kod zaten kullanılıyor.');}redirect_page('vouchers');
    }
    if($action==='delete-voucher'||$action==='toggle-voucher'){$pdo->prepare($action==='delete-voucher'?'DELETE FROM pelish_vouchers WHERE id=?':'UPDATE pelish_vouchers SET is_active=IF(is_active=1,0,1) WHERE id=?')->execute([(int)$_POST['id']]);admin_flash('success',$action==='delete-voucher'?'Hediye çeki silindi.':'Hediye çeki durumu güncellendi.');redirect_page('vouchers');}
    if ($action === 'save-order') {
        $customer=(int)($_POST['customer_id']??0);$productId=(int)($_POST['product_id']??0);$quantity=max(1,(int)($_POST['quantity']??1));$st=$pdo->prepare('SELECT * FROM pelish_products WHERE id=? AND is_active=1');$st->execute([$productId]);$product=$st->fetch();if(!$customer||!$product||(int)$product['stock']<$quantity){admin_flash('danger','Müşteri ve stokta yeterli aktif ürün seçmelisiniz.');redirect_page('orders',['new'=>1]);}$total=(float)$product['sale_price']*$quantity;$pdo->beginTransaction();try{$number='PLS-'.date('Ymd').'-'.strtoupper(substr(bin2hex(random_bytes(3)),0,6));$pdo->prepare('INSERT INTO pelish_orders (order_number,customer_id,payment_method,cargo_company,subtotal,grand_total,note) VALUES (?,?,?,?,?,?,?)')->execute([$number,$customer,form_value('payment_method','Kredi Kartı'),form_value('cargo_company')?:null,$total,$total,form_value('note')?:null]);$orderId=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO pelish_order_items (order_id,product_id,product_name,sku,unit_price,quantity) VALUES (?,?,?,?,?,?)')->execute([$orderId,$product['id'],$product['name'],$product['sku'],$product['sale_price'],$quantity]);$pdo->prepare('UPDATE pelish_products SET stock=stock-? WHERE id=? AND stock>=?')->execute([$quantity,$productId,$quantity]);$pdo->commit();admin_flash('success',$number.' numaralı sipariş oluşturuldu.');}catch(Throwable $e){$pdo->rollBack();admin_flash('danger','Sipariş kaydedilemedi.');}redirect_page('orders');
    }
    if($action==='update-order'){$allowed=['Yeni','Hazırlanıyor','Kargoda','Teslim Edildi','İptal'];$status=(string)($_POST['status']??'Yeni');if(in_array($status,$allowed,true)){$pdo->prepare('UPDATE pelish_orders SET status=?,cargo_company=?,cargo_tracking=? WHERE id=?')->execute([$status,form_value('cargo_company')?:null,form_value('cargo_tracking')?:null,(int)$_POST['id']]);admin_flash('success','Sipariş durumu güncellendi.');}redirect_page('orders');}
    if($action==='save-catalog'){$id=(int)($_POST['id']??0);$type=in_array($_POST['type']??'', ['categories','brands','tags'],true)?$_POST['type']:'categories';$name=form_value('name');if($name===''){admin_flash('danger','Kayıt adı zorunludur.');redirect_page('catalog',['type'=>$type,'new'=>1]);}$data=['type'=>$type,'name'=>$name,'slug'=>form_value('slug')?:slug_name($name),'description'=>form_value('description')?:null,'is_active'=>form_active()];try{if($id){$data['id']=$id;$pdo->prepare('UPDATE pelish_catalog_items SET name=:name,slug=:slug,description=:description,is_active=:is_active WHERE id=:id AND type=:type')->execute($data);}else{$pdo->prepare('INSERT INTO pelish_catalog_items (type,name,slug,description,is_active) VALUES (:type,:name,:slug,:description,:is_active)')->execute($data);}admin_flash('success',$id?'Katalog kaydı güncellendi.':'Katalog kaydı eklendi.');}catch(PDOException $e){admin_flash('danger','Bu bağlantı adı zaten kullanılıyor.');}redirect_page('catalog',['type'=>$type]);}
    if($action==='delete-catalog'||$action==='toggle-catalog'){$type=in_array($_POST['type']??'', ['categories','brands','tags'],true)?$_POST['type']:'categories';$pdo->prepare($action==='delete-catalog'?'DELETE FROM pelish_catalog_items WHERE id=? AND type=?':'UPDATE pelish_catalog_items SET is_active=IF(is_active=1,0,1) WHERE id=? AND type=?')->execute([(int)$_POST['id'],$type]);admin_flash('success',$action==='delete-catalog'?'Kayıt silindi.':'Kayıt durumu güncellendi.');redirect_page('catalog',['type'=>$type]);}
}

function dashboard(PDO $pdo): void {
  $m=$pdo->query("SELECT (SELECT COUNT(*) FROM pelish_products WHERE is_active=1) products,(SELECT COUNT(*) FROM pelish_orders WHERE DATE(created_at)=CURDATE()) orders,(SELECT COALESCE(SUM(grand_total),0) FROM pelish_orders WHERE DATE(created_at)=CURDATE() AND status<>'İptal') revenue,(SELECT COUNT(*) FROM pelish_customers) customers")->fetch();$recent=$pdo->query('SELECT o.*,CONCAT(c.first_name," ",c.last_name) customer FROM pelish_orders o LEFT JOIN pelish_customers c ON c.id=o.customer_id ORDER BY o.id DESC LIMIT 6')->fetchAll();$low=$pdo->query('SELECT * FROM pelish_products WHERE stock<=5 ORDER BY stock LIMIT 6')->fetchAll();
  panel_header('dashboard','Ana Sayfa',[['label'=>'Genel Bakış','href'=>admin_url('dashboard'),'active'=>true],['label'=>'Hızlı İşlemler','href'=>'#quick']]);?>
  <section class="licence-card"><div class="licence-icon"><i class="fa-solid fa-sparkles"></i></div><div><strong>Hoş geldin, Pelish.</strong><p>Mağazanın günlük özetini, siparişlerini ve stok hareketlerini buradan takip edebilirsin.</p></div><a href="<?=admin_url('orders',['new'=>1])?>"><i class="fa-solid fa-plus"></i> Yeni Sipariş</a></section>
  <section class="stat-grid dashboard-stats"><article><span>AKTİF ÜRÜNLER</span><strong><?= (int)$m['products']?></strong><i class="fa-solid fa-boxes-stacked"></i></article><article><span>BUGÜN SİPARİŞ</span><strong><?= (int)$m['orders']?></strong><i class="fa-solid fa-bag-shopping"></i></article><article><span>BUGÜN CİRO</span><strong><?=admin_money((float)$m['revenue'])?></strong><i class="fa-solid fa-chart-line"></i></article><article><span>TOPLAM MÜŞTERİ</span><strong><?= (int)$m['customers']?></strong><i class="fa-solid fa-users"></i></article></section>
  <section class="dashboard-grid" id="quick"><article class="table-card"><div class="table-title"><div><span>SİPARİŞLER</span><h1>Son siparişler</h1></div><a class="button ghost" href="<?=admin_url('orders')?>">Tümü</a></div><div class="compact-list"><?php foreach($recent as $o):?><a class="compact-row" href="<?=admin_url('orders',['edit'=>$o['id']])?>"><span class="list-icon"><i class="fa-solid fa-receipt"></i></span><span><strong><?=e($o['order_number'])?></strong><small><?=e($o['customer']?:'Misafir müşteri')?></small></span><b><?=admin_money((float)$o['grand_total'])?></b><em class="pill <?=e(slug_name($o['status']))?>"><?=e($o['status'])?></em></a><?php endforeach;if(!$recent):?><div class="empty-state"><i class="fa-solid fa-bag-shopping"></i><strong>Henüz sipariş yok.</strong></div><?php endif?></div></article><article class="table-card"><div class="table-title"><div><span>STOK UYARISI</span><h1>Azalan stoklar</h1></div><a class="button ghost" href="<?=admin_url('products')?>">Ürünler</a></div><div class="compact-list"><?php foreach($low as $p):?><a class="compact-row" href="<?=admin_url('products',['edit'=>$p['id']])?>"><span class="list-icon muted"><i class="fa-solid fa-box"></i></span><span><strong><?=e($p['name'])?></strong><small><?=e($p['sku'])?></small></span><b class="<?=!$p['stock']?'negative':''?>"><?= (int)$p['stock']?> adet</b></a><?php endforeach;if(!$low):?><div class="empty-state"><i class="fa-solid fa-circle-check"></i><strong>Stok seviyesi güvenli.</strong></div><?php endif?></div></article></section>
  <section class="quick-action-grid"><a href="<?=admin_url('products',['new'=>1])?>"><i class="fa-solid fa-box-open"></i><span>Yeni ürün ekle</span><small>Stok ve fiyat tanımla</small></a><a href="<?=admin_url('customers',['new'=>1])?>"><i class="fa-solid fa-user-plus"></i><span>Müşteri ekle</span><small>Müşteri kartı oluştur</small></a><a href="<?=admin_url('vouchers',['new'=>1])?>"><i class="fa-solid fa-ticket"></i><span>Hediye çeki oluştur</span><small>Kampanya tanımla</small></a><a href="<?=admin_url('reports')?>"><i class="fa-solid fa-chart-pie"></i><span>Raporları incele</span><small>Satış performansını gör</small></a></section><?php panel_footer();
}

function products(PDO $pdo): void {
  $q=trim((string)($_GET['q']??''));$status=(string)($_GET['status']??'all');$where=[];$args=[];if($q!==''){$where[]='(name LIKE ? OR sku LIKE ? OR barcode LIKE ? OR category LIKE ?)';$args=array_fill(0,4,'%'.$q.'%');}if($status==='active')$where[]='is_active=1';if($status==='passive')$where[]='is_active=0';if($status==='stock')$where[]='stock>0';if($status==='out-of-stock')$where[]='stock=0';$st=$pdo->prepare('SELECT * FROM pelish_products'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY id DESC');$st->execute($args);$items=$st->fetchAll();$m=$pdo->query('SELECT COUNT(*) total,SUM(is_active=1) active,COALESCE(SUM(stock),0) stock,SUM(stock=0) empty_stock FROM pelish_products')->fetch();$edit=null;if(isset($_GET['edit'])){$st=$pdo->prepare('SELECT * FROM pelish_products WHERE id=?');$st->execute([(int)$_GET['edit']]);$edit=$st->fetch()?:null;}$f=$edit?:['id'=>'','name'=>'','category'=>'','sku'=>'','barcode'=>'','image_url'=>'','sale_price'=>'','list_price'=>'','cost_price'=>'','stock'=>0,'desi'=>0,'is_active'=>1];
  panel_header('products','Ürün Yönetimi',[['label'=>'Ürünler','href'=>admin_url('products'),'active'=>true],['label'=>'Kategoriler','href'=>admin_url('catalog',['type'=>'categories'])],['label'=>'Markalar','href'=>admin_url('catalog',['type'=>'brands'])],['label'=>'Etiketler','href'=>admin_url('catalog',['type'=>'tags'])]]);?>
  <section class="licence-card"><div class="licence-icon"><i class="fa-solid fa-store"></i></div><div><strong>Ürün kataloğun hazır.</strong><p>Ürün, stok, fiyat ve yayın görünürlüğünü bu ekrandan doğrudan yönetebilirsin.</p></div><a href="<?=admin_url('products',['new'=>1])?>"><i class="fa-solid fa-plus"></i> Yeni Ürün</a></section><section class="stat-grid"><article><span>TOPLAM ÜRÜN</span><strong><?= (int)$m['total']?></strong><i class="fa-solid fa-boxes-stacked"></i></article><article><span>AKTİF ÜRÜN</span><strong><?= (int)$m['active']?></strong><i class="fa-solid fa-circle-check"></i></article><article><span>TOPLAM STOK</span><strong><?= (int)$m['stock']?></strong><i class="fa-solid fa-cubes"></i></article><article><span>STOKTA YOK</span><strong><?= (int)$m['empty_stock']?></strong><i class="fa-solid fa-triangle-exclamation"></i></article></section>
  <section class="filter-card"><form method="get" class="filters"><input type="hidden" name="page" value="products"><label class="quick-search"><i class="fa-solid fa-magnifying-glass"></i><input name="q" value="<?=e($q)?>" placeholder="Ürün adı, kodu veya barkod ara…"></label><select name="status"><option value="all">Tüm ürünler</option><?php option_list(['active'=>'Aktif ürünler','passive'=>'Pasif ürünler','stock'=>'Stokta olanlar','out-of-stock'=>'Stokta olmayanlar'],$status)?></select><button class="button info"><i class="fa-solid fa-filter"></i> Filtrele</button><a class="button ghost" href="<?=admin_url('products')?>">Temizle</a></form></section>
  <section class="table-card"><div class="table-title"><div><span>ÜRÜNLER</span><h1>Ürün listesi</h1></div><a class="button primary" href="<?=admin_url('products',['new'=>1])?>"><i class="fa-solid fa-plus"></i> Yeni Ürün</a></div><div class="table-scroll"><table><thead><tr><th>No</th><th>Resim</th><th>Ürün Bilgileri</th><th>Site</th><th>Desi</th><th>Stok</th><th>İşlemler</th></tr></thead><tbody><?php foreach($items as $p):?><tr><td><a class="product-no" href="<?=admin_url('products',['edit'=>$p['id']])?>">#<?= (int)$p['id']?></a></td><td><a class="product-image" href="<?=admin_url('products',['edit'=>$p['id']])?>"><img src="<?=e($p['image_url']?:'https://cdn.lavira360.com/pelish/logo.png')?>" alt="<?=e($p['name'])?>"></a></td><td class="product-info"><a href="<?=admin_url('products',['edit'=>$p['id']])?>"><strong><?=e($p['name'])?></strong></a><span>Kategori: <b><?=e($p['category'])?></b></span><span>Kodu: <b><?=e($p['sku'])?></b></span><span>Barkod: <b><?=e($p['barcode']?:'-')?></b></span></td><td class="price-cell"><form method="post" class="status-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="toggle-product"><input type="hidden" name="id" value="<?= (int)$p['id']?>"><button class="status <?=$p['is_active']?'on':''?>"><i class="fa-regular fa-circle-check"></i></button></form><strong><?=admin_money((float)$p['sale_price'])?></strong><span>P: <?=admin_money((float)$p['list_price'])?></span></td><td><?=number_format((float)$p['desi'],1,',','.')?></td><td><strong class="stock <?=!$p['stock']?'empty':''?>"><?= (int)$p['stock']?></strong></td><td><div class="row-actions"><a href="<?=admin_url('products',['edit'=>$p['id']])?>"><i class="fa-solid fa-pen"></i></a><a href="../urun.html?id=luna-saten-elbise" target="_blank"><i class="fa-solid fa-arrow-up-right-from-square"></i></a><?php confirm_button('delete-product',(int)$p['id'],'Bu ürün kalıcı olarak silinsin mi?')?></div></td></tr><?php endforeach;if(!$items):?><tr><td colspan="7" class="empty-table"><i class="fa-solid fa-box-open"></i><strong>Ürün bulunamadı.</strong></td></tr><?php endif?></tbody></table></div></section>
  <?php ob_start();?><form method="post" class="product-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save-product"><input type="hidden" name="id" value="<?= (int)$f['id']?>"><div class="form-grid"><label class="wide">Ürün adı<input required name="name" value="<?=e($f['name'])?>"></label><label>Kategori<input name="category" value="<?=e($f['category'])?>"></label><label>Ürün kodu<input required name="sku" value="<?=e($f['sku'])?>"></label><label>Barkod<input name="barcode" value="<?=e($f['barcode'])?>"></label><label>Görsel bağlantısı<input name="image_url" value="<?=e($f['image_url'])?>"></label><label>Satış fiyatı<input type="number" step="0.01" min="0" required name="sale_price" value="<?=e((string)$f['sale_price'])?>"></label><label>Liste fiyatı<input type="number" step="0.01" min="0" name="list_price" value="<?=e((string)$f['list_price'])?>"></label><label>Alış fiyatı<input type="number" step="0.01" min="0" name="cost_price" value="<?=e((string)$f['cost_price'])?>"></label><label>Stok<input type="number" min="0" required name="stock" value="<?= (int)$f['stock']?>"></label><label>Desi<input type="number" step="0.1" min="0" name="desi" value="<?=e((string)$f['desi'])?>"></label><label class="switch-line"><input type="checkbox" name="is_active" <?=$f['is_active']?'checked':''?>> Sitede aktif</label></div><div class="modal-actions"><a class="button ghost" href="<?=admin_url('products')?>">İptal</a><button class="button primary">Kaydet</button></div></form><?php modal('products','ÜRÜN YÖNETİMİ',$edit?'Ürünü düzenle':'Yeni ürün',ob_get_clean());panel_footer();
}

function orders(PDO $pdo): void {
  $st=$pdo->query('SELECT o.*,CONCAT(c.first_name," ",c.last_name) customer,c.email FROM pelish_orders o LEFT JOIN pelish_customers c ON c.id=o.customer_id ORDER BY o.id DESC');$items=$st->fetchAll();$m=$pdo->query("SELECT COUNT(*) total,SUM(status='Yeni') new_orders,SUM(status='Kargoda') cargo,COALESCE(SUM(CASE WHEN status<>'İptal' THEN grand_total ELSE 0 END),0) revenue FROM pelish_orders")->fetch();$customers=$pdo->query('SELECT id,first_name,last_name,email FROM pelish_customers WHERE is_active=1 ORDER BY first_name')->fetchAll();$products=$pdo->query('SELECT id,name,sale_price,stock FROM pelish_products WHERE is_active=1 AND stock>0 ORDER BY name')->fetchAll();$edit=null;if(isset($_GET['edit'])){$st=$pdo->prepare('SELECT * FROM pelish_orders WHERE id=?');$st->execute([(int)$_GET['edit']]);$edit=$st->fetch()?:null;}
  panel_header('orders','Sipariş Yönetimi',[['label'=>'Siparişler','href'=>admin_url('orders'),'active'=>true],['label'=>'Yeni Sipariş','href'=>admin_url('orders',['new'=>1])],['label'=>'Raporlar','href'=>admin_url('reports')]]);?>
  <section class="licence-card"><div class="licence-icon"><i class="fa-solid fa-bag-shopping"></i></div><div><strong>Sipariş akışın kontrol altında.</strong><p>Yeni sipariş oluştur, kargo bilgisini ekle ve durumunu anlık olarak güncelle.</p></div><a href="<?=admin_url('orders',['new'=>1])?>"><i class="fa-solid fa-plus"></i> Yeni Sipariş</a></section><section class="stat-grid"><article><span>TOPLAM SİPARİŞ</span><strong><?= (int)$m['total']?></strong><i class="fa-solid fa-receipt"></i></article><article><span>YENİ SİPARİŞ</span><strong><?= (int)$m['new_orders']?></strong><i class="fa-solid fa-bell"></i></article><article><span>KARGODAKİLER</span><strong><?= (int)$m['cargo']?></strong><i class="fa-solid fa-truck-fast"></i></article><article><span>TOPLAM CİRO</span><strong><?=admin_money((float)$m['revenue'])?></strong><i class="fa-solid fa-chart-line"></i></article></section>
  <section class="table-card"><div class="table-title"><div><span>SİPARİŞLER</span><h1>Sipariş listesi</h1></div><a class="button primary" href="<?=admin_url('orders',['new'=>1])?>"><i class="fa-solid fa-plus"></i> Yeni Sipariş</a></div><div class="table-scroll"><table><thead><tr><th>Sipariş No</th><th>Müşteri</th><th>Tarih</th><th>Ödeme</th><th>Durum</th><th>Tutar</th><th>İşlem</th></tr></thead><tbody><?php foreach($items as $o):?><tr><td><a class="product-no" href="<?=admin_url('orders',['edit'=>$o['id']])?>"><?=e($o['order_number'])?></a></td><td><strong><?=e($o['customer']?:'Misafir müşteri')?></strong><br><span class="cell-muted"><?=e($o['email']?:'-')?></span></td><td><?=date('d.m.Y H:i',strtotime($o['created_at']))?></td><td><?=e($o['payment_method'])?></td><td><span class="pill <?=e(slug_name($o['status']))?>"><?=e($o['status'])?></span></td><td><strong><?=admin_money((float)$o['grand_total'])?></strong></td><td><a class="button ghost small" href="<?=admin_url('orders',['edit'=>$o['id']])?>">Yönet</a></td></tr><?php endforeach;if(!$items):?><tr><td colspan="7" class="empty-table"><i class="fa-solid fa-receipt"></i><strong>Henüz sipariş yok.</strong></td></tr><?php endif?></tbody></table></div></section>
  <?php ob_start();if($edit):?><form method="post" class="product-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="update-order"><input type="hidden" name="id" value="<?= (int)$edit['id']?>"><div class="order-summary"><span><?=e($edit['order_number'])?></span><strong><?=admin_money((float)$edit['grand_total'])?></strong></div><div class="form-grid"><label>Durum<select name="status"><?php option_list(['Yeni','Hazırlanıyor','Kargoda','Teslim Edildi','İptal'],$edit['status'])?></select></label><label>Kargo firması<input name="cargo_company" value="<?=e($edit['cargo_company']??'')?>"></label><label class="wide">Kargo takip numarası<input name="cargo_tracking" value="<?=e($edit['cargo_tracking']??'')?>"></label></div><div class="modal-actions"><a class="button ghost" href="<?=admin_url('orders')?>">İptal</a><button class="button primary">Durumu Güncelle</button></div></form><?php else:?><form method="post" class="product-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save-order"><div class="form-grid"><label>Müşteri<select name="customer_id" required><option value="">Müşteri seçin</option><?php foreach($customers as $c):?><option value="<?=$c['id']?>"><?=e($c['first_name'].' '.$c['last_name'].' · '.$c['email'])?></option><?php endforeach?></select></label><label>Ürün<select name="product_id" required><option value="">Ürün seçin</option><?php foreach($products as $p):?><option value="<?=$p['id']?>"><?=e($p['name'].' · '.admin_money((float)$p['sale_price']).' · '.$p['stock'].' stok')?></option><?php endforeach?></select></label><label>Adet<input type="number" min="1" value="1" name="quantity"></label><label>Ödeme<select name="payment_method"><?php option_list(['Kredi Kartı','Havale / EFT','Kapıda Ödeme'])?></select></label><label>Kargo firması<input name="cargo_company"></label><label class="wide">Sipariş notu<textarea name="note"></textarea></label></div><div class="modal-actions"><a class="button ghost" href="<?=admin_url('orders')?>">İptal</a><button class="button primary">Siparişi Oluştur</button></div></form><?php endif;modal('orders','SİPARİŞ YÖNETİMİ',$edit?'Siparişi güncelle':'Yeni sipariş',ob_get_clean());panel_footer();
}

function marketplaces(PDO $pdo): void {
  $items=$pdo->query('SELECT * FROM pelish_marketplaces ORDER BY id DESC')->fetchAll();$edit=null;if(isset($_GET['edit'])){$s=$pdo->prepare('SELECT * FROM pelish_marketplaces WHERE id=?');$s->execute([(int)$_GET['edit']]);$edit=$s->fetch()?:null;}$f=$edit?:['id'=>'','name'=>'','marketplace'=>'Trendyol','store_code'=>'','commission_rate'=>0,'is_active'=>1];panel_header('marketplaces','Pazaryeri Mağazaları',[['label'=>'Mağazalar','href'=>admin_url('marketplaces'),'active'=>true],['label'=>'Yeni Mağaza','href'=>admin_url('marketplaces',['new'=>1])]]);?>
  <section class="licence-card"><div class="licence-icon"><i class="fa-solid fa-store"></i></div><div><strong>Satış kanallarını tek yerden yönet.</strong><p>Mağaza tanımlarını, komisyon oranlarını ve senkronizasyon zamanlarını güncel tut.</p></div><a href="<?=admin_url('marketplaces',['new'=>1])?>"><i class="fa-solid fa-plus"></i> Mağaza Ekle</a></section><section class="table-card"><div class="table-title"><div><span>PAZARYERİ</span><h1>Bağlı mağazalar</h1></div><a class="button primary" href="<?=admin_url('marketplaces',['new'=>1])?>"><i class="fa-solid fa-plus"></i> Mağaza Ekle</a></div><div class="table-scroll"><table><thead><tr><th>Mağaza</th><th>Pazaryeri</th><th>Kod</th><th>Komisyon</th><th>Son Senkronizasyon</th><th>Durum</th><th>İşlemler</th></tr></thead><tbody><?php foreach($items as $i):?><tr><td><strong><?=e($i['name'])?></strong></td><td><span class="market-badge"><?=e($i['marketplace'])?></span></td><td><?=e($i['store_code']?:'-')?></td><td>%<?=number_format((float)$i['commission_rate'],2,',','.')?></td><td><?=$i['last_sync_at']?date('d.m.Y H:i',strtotime($i['last_sync_at'])):'Henüz yok'?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="toggle-marketplace"><input type="hidden" name="id" value="<?=$i['id']?>"><button class="status <?=$i['is_active']?'on':''?>"><i class="fa-regular fa-circle-check"></i> <?=$i['is_active']?'Aktif':'Pasif'?></button></form></td><td><div class="row-actions wide-actions"><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="sync-marketplace"><input type="hidden" name="id" value="<?=$i['id']?>"><button><i class="fa-solid fa-rotate"></i></button></form><a href="<?=admin_url('marketplaces',['edit'=>$i['id']])?>"><i class="fa-solid fa-pen"></i></a><?php confirm_button('delete-marketplace',(int)$i['id'],'Bu mağaza silinsin mi?')?></div></td></tr><?php endforeach?></tbody></table></div></section>
  <?php ob_start();?><form method="post" class="product-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save-marketplace"><input type="hidden" name="id" value="<?=$f['id']?>"><div class="form-grid"><label class="wide">Mağaza adı<input required name="name" value="<?=e($f['name'])?>"></label><label>Pazaryeri<select name="marketplace"><?php option_list(['Trendyol','Hepsiburada','n11','ÇiçekSepeti','Amazon'],$f['marketplace'])?></select></label><label>Mağaza kodu<input name="store_code" value="<?=e($f['store_code'])?>"></label><label>Komisyon oranı (%)<input type="number" step="0.01" min="0" name="commission_rate" value="<?=e((string)$f['commission_rate'])?>"></label><label class="switch-line"><input type="checkbox" name="is_active" <?=$f['is_active']?'checked':''?>> Mağaza aktif</label></div><div class="modal-actions"><a href="<?=admin_url('marketplaces')?>" class="button ghost">İptal</a><button class="button primary">Kaydet</button></div></form><?php modal('marketplaces','PAZARYERİ',$edit?'Mağazayı düzenle':'Yeni pazaryeri mağazası',ob_get_clean());panel_footer();
}

function vouchers(PDO $pdo): void {
  $items=$pdo->query('SELECT * FROM pelish_vouchers ORDER BY id DESC')->fetchAll();$edit=null;if(isset($_GET['edit'])){$s=$pdo->prepare('SELECT * FROM pelish_vouchers WHERE id=?');$s->execute([(int)$_GET['edit']]);$edit=$s->fetch()?:null;}$f=$edit?:['id'=>'','code'=>'','title'=>'','amount_type'=>'percent','amount'=>'','min_cart_total'=>0,'usage_limit'=>'','starts_at'=>'','ends_at'=>'','is_active'=>1];panel_header('vouchers','Hediye Çekleri',[['label'=>'Hediye Çekleri','href'=>admin_url('vouchers'),'active'=>true],['label'=>'Yeni Hediye Çeki','href'=>admin_url('vouchers',['new'=>1])]]);?>
  <section class="licence-card"><div class="licence-icon"><i class="fa-solid fa-ticket"></i></div><div><strong>Kampanyalarını yönet.</strong><p>İndirim kodu, kullanım limiti ve geçerlilik tarihlerini doğrudan bu alandan tanımla.</p></div><a href="<?=admin_url('vouchers',['new'=>1])?>"><i class="fa-solid fa-plus"></i> Yeni Hediye Çeki</a></section><section class="table-card"><div class="table-title"><div><span>KAMPANYALAR</span><h1>Hediye çeki listesi</h1></div><a class="button primary" href="<?=admin_url('vouchers',['new'=>1])?>"><i class="fa-solid fa-plus"></i> Yeni Hediye Çeki</a></div><div class="table-scroll"><table><thead><tr><th>Kod</th><th>Başlık</th><th>İndirim</th><th>Alt Limit</th><th>Kullanım</th><th>Geçerlilik</th><th>Durum</th><th>İşlemler</th></tr></thead><tbody><?php foreach($items as $i):?><tr><td><strong class="voucher-code"><?=e($i['code'])?></strong></td><td><?=e($i['title'])?></td><td><?=$i['amount_type']==='percent'?'%'.number_format((float)$i['amount'],0):admin_money((float)$i['amount'])?></td><td><?=admin_money((float)$i['min_cart_total'])?></td><td><?=$i['usage_count']?><?=$i['usage_limit']!==null?' / '.$i['usage_limit']:''?></td><td><span class="cell-muted"><?=$i['starts_at']?date('d.m.Y',strtotime($i['starts_at'])):'Hemen'?> — <?=$i['ends_at']?date('d.m.Y',strtotime($i['ends_at'])):'Süresiz'?></span></td><td><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="toggle-voucher"><input type="hidden" name="id" value="<?=$i['id']?>"><button class="status <?=$i['is_active']?'on':''?>"><i class="fa-regular fa-circle-check"></i> <?=$i['is_active']?'Aktif':'Pasif'?></button></form></td><td><div class="row-actions"><a href="<?=admin_url('vouchers',['edit'=>$i['id']])?>"><i class="fa-solid fa-pen"></i></a><?php confirm_button('delete-voucher',(int)$i['id'],'Bu hediye çeki silinsin mi?')?></div></td></tr><?php endforeach?></tbody></table></div></section>
  <?php ob_start();?><form method="post" class="product-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save-voucher"><input type="hidden" name="id" value="<?=$f['id']?>"><div class="form-grid"><label>Kupon kodu<input required name="code" value="<?=e($f['code'])?>"></label><label>Başlık<input required name="title" value="<?=e($f['title'])?>"></label><label>İndirim tipi<select name="amount_type"><option value="percent" <?=$f['amount_type']==='percent'?'selected':''?>>Yüzde</option><option value="fixed" <?=$f['amount_type']==='fixed'?'selected':''?>>Sabit tutar</option></select></label><label>İndirim miktarı<input required type="number" min="0" step="0.01" name="amount" value="<?=e((string)$f['amount'])?>"></label><label>Minimum sepet tutarı<input type="number" min="0" step="0.01" name="min_cart_total" value="<?=e((string)$f['min_cart_total'])?>"></label><label>Kullanım limiti<input type="number" min="0" name="usage_limit" value="<?=e((string)$f['usage_limit'])?>"></label><label>Başlangıç<input type="datetime-local" name="starts_at" value="<?=e($f['starts_at']?date('Y-m-d\\TH:i',strtotime($f['starts_at'])):'')?>"></label><label>Bitiş<input type="datetime-local" name="ends_at" value="<?=e($f['ends_at']?date('Y-m-d\\TH:i',strtotime($f['ends_at'])):'')?>"></label><label class="switch-line"><input type="checkbox" name="is_active" <?=$f['is_active']?'checked':''?>> Kullanıma açık</label></div><div class="modal-actions"><a href="<?=admin_url('vouchers')?>" class="button ghost">İptal</a><button class="button primary">Kaydet</button></div></form><?php modal('vouchers','KAMPANYALAR',$edit?'Hediye çekini düzenle':'Yeni hediye çeki',ob_get_clean());panel_footer();
}

function customers(PDO $pdo): void {
  $q=trim((string)($_GET['q']??''));$s=$pdo->prepare('SELECT c.*,COUNT(o.id) order_count,COALESCE(SUM(o.grand_total),0) total_spend FROM pelish_customers c LEFT JOIN pelish_orders o ON o.customer_id=c.id WHERE CONCAT(c.first_name," ",c.last_name) LIKE ? OR c.email LIKE ? GROUP BY c.id ORDER BY c.id DESC');$s->execute(['%'.$q.'%','%'.$q.'%']);$items=$s->fetchAll();$edit=null;if(isset($_GET['edit'])){$s=$pdo->prepare('SELECT * FROM pelish_customers WHERE id=?');$s->execute([(int)$_GET['edit']]);$edit=$s->fetch()?:null;}$f=$edit?:['id'=>'','first_name'=>'','last_name'=>'','email'=>'','phone'=>'','city'=>'Tekirdağ','district'=>'Süleymanpaşa','is_active'=>1];panel_header('customers','Müşteriler',[['label'=>'Müşteri Listesi','href'=>admin_url('customers'),'active'=>true],['label'=>'Yeni Müşteri','href'=>admin_url('customers',['new'=>1])],['label'=>'Siparişler','href'=>admin_url('orders')]]);?>
  <section class="licence-card"><div class="licence-icon"><i class="fa-solid fa-users"></i></div><div><strong>Müşteri ilişkilerini güçlendir.</strong><p>Müşteri kartlarını ve alışveriş geçmişini tek bir görünümde takip et.</p></div><a href="<?=admin_url('customers',['new'=>1])?>"><i class="fa-solid fa-user-plus"></i> Yeni Müşteri</a></section><section class="filter-card"><form method="get" class="filters"><input type="hidden" name="page" value="customers"><label class="quick-search"><i class="fa-solid fa-magnifying-glass"></i><input name="q" value="<?=e($q)?>" placeholder="Ad soyad veya e-posta ara…"></label><button class="button info">Ara</button><a class="button ghost" href="<?=admin_url('customers')?>">Temizle</a></form></section><section class="table-card"><div class="table-title"><div><span>MÜŞTERİLER</span><h1>Müşteri listesi</h1></div><a class="button primary" href="<?=admin_url('customers',['new'=>1])?>"><i class="fa-solid fa-user-plus"></i> Yeni Müşteri</a></div><div class="table-scroll"><table><thead><tr><th>Müşteri</th><th>İletişim</th><th>Konum</th><th>Sipariş</th><th>Toplam Harcama</th><th>Durum</th><th>İşlemler</th></tr></thead><tbody><?php foreach($items as $i):?><tr><td><strong><?=e($i['first_name'].' '.$i['last_name'])?></strong><br><span class="cell-muted">#<?=$i['id']?></span></td><td><?=e($i['email'])?><br><span class="cell-muted"><?=e($i['phone']?:'-')?></span></td><td><?=e(trim(($i['district']?:'').($i['city']?', '.$i['city']:''),', ')?:'-')?></td><td><?=$i['order_count']?></td><td><strong><?=admin_money((float)$i['total_spend'])?></strong></td><td><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="toggle-customer"><input type="hidden" name="id" value="<?=$i['id']?>"><button class="status <?=$i['is_active']?'on':''?>"><i class="fa-regular fa-circle-check"></i> <?=$i['is_active']?'Aktif':'Pasif'?></button></form></td><td><div class="row-actions"><a href="<?=admin_url('customers',['edit'=>$i['id']])?>"><i class="fa-solid fa-pen"></i></a><?php confirm_button('delete-customer',(int)$i['id'],'Bu müşteri silinsin mi?')?></div></td></tr><?php endforeach?></tbody></table></div></section>
  <?php ob_start();?><form method="post" class="product-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save-customer"><input type="hidden" name="id" value="<?=$f['id']?>"><div class="form-grid"><label>Ad<input required name="first_name" value="<?=e($f['first_name'])?>"></label><label>Soyad<input required name="last_name" value="<?=e($f['last_name'])?>"></label><label class="wide">E-posta<input required type="email" name="email" value="<?=e($f['email'])?>"></label><label>Telefon<input name="phone" value="<?=e($f['phone'])?>"></label><label>İl<input name="city" value="<?=e($f['city'])?>"></label><label>İlçe<input name="district" value="<?=e($f['district'])?>"></label><label class="switch-line"><input type="checkbox" name="is_active" <?=$f['is_active']?'checked':''?>> Müşteri aktif</label></div><div class="modal-actions"><a href="<?=admin_url('customers')?>" class="button ghost">İptal</a><button class="button primary">Kaydet</button></div></form><?php modal('customers','MÜŞTERİLER',$edit?'Müşteriyi düzenle':'Yeni müşteri',ob_get_clean());panel_footer();
}

function catalog(PDO $pdo): void {
  $type=in_array($_GET['type']??'', ['categories','brands','tags'],true)?$_GET['type']:'categories';$meta=['categories'=>['Kategoriler','Kategori'],'brands'=>['Markalar','Marka'],'tags'=>['Etiketler','Etiket']][$type];$s=$pdo->prepare('SELECT * FROM pelish_catalog_items WHERE type=? ORDER BY name');$s->execute([$type]);$items=$s->fetchAll();$edit=null;if(isset($_GET['edit'])){$s=$pdo->prepare('SELECT * FROM pelish_catalog_items WHERE id=? AND type=?');$s->execute([(int)$_GET['edit'],$type]);$edit=$s->fetch()?:null;}$f=$edit?:['id'=>'','name'=>'','slug'=>'','description'=>'','is_active'=>1];panel_header('catalog','Ürün Yönetimi',[['label'=>'Ürünler','href'=>admin_url('products')],['label'=>'Kategoriler','href'=>admin_url('catalog',['type'=>'categories']),'active'=>$type==='categories'],['label'=>'Markalar','href'=>admin_url('catalog',['type'=>'brands']),'active'=>$type==='brands'],['label'=>'Etiketler','href'=>admin_url('catalog',['type'=>'tags']),'active'=>$type==='tags']]);?>
  <section class="licence-card"><div class="licence-icon"><i class="fa-solid fa-folder-tree"></i></div><div><strong><?=e($meta[0])?> yönetimi.</strong><p>Ürün kataloğunda kullanılan <?=mb_strtolower($meta[0],'UTF-8')?> tanımlarını doğrudan yönet.</p></div><a href="<?=admin_url('catalog',['type'=>$type,'new'=>1])?>"><i class="fa-solid fa-plus"></i> Yeni <?=e($meta[1])?></a></section><section class="table-card"><div class="table-title"><div><span>ÜRÜN YÖNETİMİ</span><h1><?=e($meta[0])?></h1></div><a class="button primary" href="<?=admin_url('catalog',['type'=>$type,'new'=>1])?>"><i class="fa-solid fa-plus"></i> Yeni <?=e($meta[1])?></a></div><div class="table-scroll"><table><thead><tr><th>Ad</th><th>Bağlantı adı</th><th>Açıklama</th><th>Durum</th><th>İşlemler</th></tr></thead><tbody><?php foreach($items as $i):?><tr><td><strong><?=e($i['name'])?></strong></td><td><code><?=e($i['slug'])?></code></td><td><?=e($i['description']?:'-')?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="toggle-catalog"><input type="hidden" name="id" value="<?=$i['id']?>"><input type="hidden" name="type" value="<?=e($type)?>"><button class="status <?=$i['is_active']?'on':''?>"><i class="fa-regular fa-circle-check"></i> <?=$i['is_active']?'Aktif':'Pasif'?></button></form></td><td><div class="row-actions"><a href="<?=admin_url('catalog',['type'=>$type,'edit'=>$i['id']])?>"><i class="fa-solid fa-pen"></i></a><?php confirm_button('delete-catalog',(int)$i['id'],'Bu kayıt silinsin mi?',['type'=>$type])?></div></td></tr><?php endforeach?></tbody></table></div></section>
  <?php ob_start();?><form method="post" class="product-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save-catalog"><input type="hidden" name="id" value="<?=$f['id']?>"><input type="hidden" name="type" value="<?=e($type)?>"><div class="form-grid"><label>Ad<input required name="name" value="<?=e($f['name'])?>"></label><label>Bağlantı adı<input name="slug" value="<?=e($f['slug'])?>"></label><label class="wide">Açıklama<textarea name="description"><?=e($f['description'])?></textarea></label><label class="switch-line"><input type="checkbox" name="is_active" <?=$f['is_active']?'checked':''?>> Aktif</label></div><div class="modal-actions"><a href="<?=admin_url('catalog',['type'=>$type])?>" class="button ghost">İptal</a><button class="button primary">Kaydet</button></div></form><?php modal('catalog','ÜRÜN YÖNETİMİ',$edit?'Kaydı düzenle':'Yeni '.$meta[1],ob_get_clean());panel_footer();
}

function reports(PDO $pdo): void {
  $m=$pdo->query("SELECT COUNT(*) orders,COALESCE(SUM(CASE WHEN status<>'İptal' THEN grand_total ELSE 0 END),0) revenue,COALESCE(AVG(CASE WHEN status<>'İptal' THEN grand_total END),0) average_basket,SUM(status='İptal') cancelled FROM pelish_orders")->fetch();$statuses=$pdo->query('SELECT status,COUNT(*) count,COALESCE(SUM(grand_total),0) total FROM pelish_orders GROUP BY status ORDER BY count DESC')->fetchAll();$products=$pdo->query('SELECT product_name,SUM(quantity) qty,SUM(quantity*unit_price) total FROM pelish_order_items GROUP BY product_name ORDER BY qty DESC LIMIT 6')->fetchAll();$customers=$pdo->query('SELECT CONCAT(c.first_name," ",c.last_name) name,COUNT(o.id) count,COALESCE(SUM(o.grand_total),0) total FROM pelish_customers c LEFT JOIN pelish_orders o ON o.customer_id=c.id GROUP BY c.id ORDER BY total DESC LIMIT 6')->fetchAll();$max=max(array_map(static fn($x)=>(int)$x['count'],$statuses)?:[1]);panel_header('reports','Raporlar',[['label'=>'Genel Bakış','href'=>admin_url('reports'),'active'=>true],['label'=>'Siparişler','href'=>admin_url('orders')],['label'=>'Ürünler','href'=>admin_url('products')]]);?>
  <section class="licence-card"><div class="licence-icon"><i class="fa-solid fa-chart-pie"></i></div><div><strong>Satış performansını izle.</strong><p>Raporlar mevcut sipariş, ürün ve müşteri verilerinden gerçek zamanlı hesaplanır.</p></div><a href="<?=admin_url('orders',['new'=>1])?>"><i class="fa-solid fa-plus"></i> Sipariş Oluştur</a></section><section class="stat-grid"><article><span>TOPLAM CİRO</span><strong><?=admin_money((float)$m['revenue'])?></strong><i class="fa-solid fa-sack-dollar"></i></article><article><span>TOPLAM SİPARİŞ</span><strong><?=$m['orders']?></strong><i class="fa-solid fa-receipt"></i></article><article><span>ORT. SEPET</span><strong><?=admin_money((float)$m['average_basket'])?></strong><i class="fa-solid fa-basket-shopping"></i></article><article><span>İPTAL SİPARİŞ</span><strong><?=$m['cancelled']?></strong><i class="fa-solid fa-ban"></i></article></section><section class="report-grid"><article class="table-card"><div class="table-title"><div><span>SİPARİŞ DAĞILIMI</span><h1>Duruma göre siparişler</h1></div></div><div class="bar-list"><?php foreach($statuses as $s):?><div><div class="bar-label"><span><?=e($s['status'])?></span><strong><?=$s['count']?> sipariş · <?=admin_money((float)$s['total'])?></strong></div><span class="bar"><i style="width:<?=max(5,round($s['count']/$max*100))?>%"></i></span></div><?php endforeach;if(!$statuses):?><div class="empty-state"><i class="fa-solid fa-chart-simple"></i><strong>Rapor için sipariş verisi gerekiyor.</strong></div><?php endif?></div></article><article class="table-card"><div class="table-title"><div><span>ÜRÜN PERFORMANSI</span><h1>En çok satılanlar</h1></div></div><div class="compact-list"><?php foreach($products as $p):?><div class="compact-row"><span class="list-icon"><i class="fa-solid fa-box"></i></span><span><strong><?=e($p['product_name'])?></strong><small><?=$p['qty']?> adet satıldı</small></span><b><?=admin_money((float)$p['total'])?></b></div><?php endforeach?></div></article><article class="table-card report-wide"><div class="table-title"><div><span>MÜŞTERİ ANALİZİ</span><h1>En değerli müşteriler</h1></div></div><div class="table-scroll"><table><thead><tr><th>Müşteri</th><th>Sipariş Sayısı</th><th>Toplam Harcama</th></tr></thead><tbody><?php foreach($customers as $c):?><tr><td><strong><?=e($c['name'])?></strong></td><td><?=$c['count']?></td><td><strong><?=admin_money((float)$c['total'])?></strong></td></tr><?php endforeach?></tbody></table></div></article></section><?php panel_footer();
}

match($page){'products'=>products($pdo),'orders'=>orders($pdo),'marketplaces'=>marketplaces($pdo),'vouchers'=>vouchers($pdo),'customers'=>customers($pdo),'catalog'=>catalog($pdo),'reports'=>reports($pdo),default=>dashboard($pdo)};
